### ISSUE TITLE
crypt_gensalt* nrbytes recommendations?

### ISSUE THREAD

**Issue by RavuAlHemio** [besser82/libxcrypt#145]
Greetings,

are there any recommendations for the number of random bytes (`rbytes` and `nrbytes`) passed to the `crypt_gensalt` family of functions? Interestingly enough, asking for a yescrypt salt (prefix `"$y$"`) fails with `ERANGE` if too many random bytes are passed; this is not documented as one of the possible reasons for `ERANGE` in the corresponding manpage.

Perhaps one of the following options might make sense:

* Silent truncation of `rbytes` (only using as many bytes as the chosen method requires or can sanely handle).
* Providing a facility (e.g. a function) for a method to inform the caller about its preferred number of random bytes.

**Comment by besser82** [comment]
Hi,

thanks for your findings!

I assume more then 32 bytes of randomness for the salt won't offer any benefit for the `scrypt` and `yescrypt` hashing methods.  Maybe we should silently discard any higher number of `rbytes` fed into their corresponding gensalt implementations.

@zackw @solardiz How do you feel about this?

**Comment by solardiz** [comment]
I guess the recommendation for current libxcrypt should be to pass `NULL, 0` to let libxcrypt generate a random salt of an appropriate size on its own.

I agree that more than 32 is unneeded. In fact, that's already way more than is needed for security, but presumably it could be for compliance. I hope we wouldn't need more than that even for compliance later, although technically yescrypt currently supports up to 64 just in case. I don't know what the current limit in libxcrypt is, but I'm OK with truncating to that limit if it's 32 or 64 instead of returning `ERANGE`. If we continue to return that error, then that would need to be documented, but we probably should not.

Also related is what maximum the crypt(5) man page gives. I think it's currently 512 bits. If we truncate to 256 instead, we'd probably need to add a remark along the lines of "512 but new hashes set via libxcrypt are limited to 256". That's not pretty, and is probably a reason not to truncate to less than 64 bytes.

**Comment by besser82** [comment]
@solardiz Thanks for your comments.  Please let me know, if the linked PR is fine for you and aligns with your recommendations on this topic.

**Comment by besser82** [comment]
@RavuAlHemio Is the issue fixed for you with my changes in the linked PR?

**Comment by RavuAlHemio** [comment]
Yes, I just tested it and the truncation seems to work as expected -- I am no longer getting `ERANGE`.

**Comment by besser82** [comment]
> Yes, I just tested it and the truncation seems to work as expected -- I am no longer getting `ERANGE`.

Thanks for the feedback!

**Comment by RavuAlHemio** [comment]
Thanks for the speedy fix!

**Comment by solardiz** [comment]
With the changes in #146, we now recommend "128+". I'd recommend exactly 128. No need to "recommend" something that we actually should not genuinely recommend.

OTOH, this reminds me that shadow went with 144 for ease of encoding (with shadow's custom code). I'd rather see them use 128, but we possibly should not make their 144 appear not-recommended now...

We might also want to check how other `crypt_gensalt` implementations (for all other hash types supported in libxcrypt) handle excessive `nrbytes`, and if needed make them truncate at their supported maximums too (I think they aleaedy do, but this is worth double-checking).
