### ISSUE TITLE
Segfault when pass is NULL and when generating NTHashes

### ISSUE THREAD

**Issue by sedrubal** [besser82/libxcrypt#15]
Following (invalid) code will produce a segfault, because `phrase` is `NULL`:

```c
#include <crypt.h>
#include <stdio.h>

int main(int argc, const char *argv[])
{
        struct crypt_data data;
        data.initialized = 0;
        const char* hash = crypt_r((char*) NULL, "$3$$", &data);
        printf("%s\n", hash);
        return 0;
}
```

I'm not sure if this is intended. Other hashes return "*0", when `pass` is `NULL`.

**Comment by zackw** [comment]
Clearly the behavior should not depend on which hashing method is in use.

There is an argument that passing NULL as `phrase` should return `*0` for all hashes, but there is also an argument that it should _crash_ for all hashes.  (See https://blogs.msdn.microsoft.com/oldnewthing/20060927-07/?p=29563 and also consider what happens if you pass a pointer to five `'a'`s followed by unmapped address space as `phrase`; we _can't_ reliably do anything other than crash in that case.)

@besser82 which seems more appropriate to you?

**Comment by besser82** [comment]
Passing in `NULL` as `phrase` should return `*0` and set `errno = EINVAL` with all hashes, since passing a pointer to `NULL` is a valid parameter by the C-standard; checking for a `NULL` pointer is valid and doesn't cause random side-effects.  Thus we should signal an error in that case.

**Comment by zackw** [comment]
Which bit of the C standard are you thinking of?  The general rule is that passing NULL to a C library function provokes undefined behavior (7.1.4p1, very first sentence):

> Each of the following statements applies unless explicitly stated otherwise in the detailed
descriptions that follow: If an argument to a function has an invalid value (such as a value
outside the domain of the function, or a pointer outside the address space of the program,
or a null pointer, or a pointer to non-modifiable storage when the corresponding
parameter is not const-qualified) or a type (after promotion) not expected by a function
with variable number of arguments, the behavior is undefined.

`crypt` itself isn't in C, but it _is_ in POSIX, so that spec could "explicitly state otherwise", but it doesn't: compare the language about the _key_ argument in  http://pubs.opengroup.org/onlinepubs/9699919799/functions/crypt.html to the language about the _ptr_ argument in http://pubs.opengroup.org/onlinepubs/9699919799/functions/free.html .

**Comment by besser82** [comment]
Fixed in https://github.com/besser82/libxcrypt/commit/aae4c1baea534d2e4c9dfe2faf42ee0c5f7a6f22.  I'll do a bugfix release over the weekend.

Closing here as this is fixed.
