### ISSUE TITLE
Upstreaming gost-yescrypt from ALT Linux?

### ISSUE THREAD

**Issue by besser82** [besser82/libxcrypt#33]
@vt-alt, @ldv-alt:  What about implementing `$gy$` upstream?  Do you have any plans doing that?  It might be useful for the users of Fedora русский Remix as well.

**Comment by vt-alt** [comment]
Yes, we have plans to upstream it too. It is also designed with @solardiz. It would be useful for people wanting modern password hashing, but requiring (or preferring) to rely on cryptographic properties of GOST algorithms.

**Comment by besser82** [comment]
Sounds good.

I've seen you are using the OpenSSL implementation of the [Streebog Hash Function][1].  The [canonical implementation][2] seems to have a more permissive license (BSD 2-clause), which is preferred for libxcrypt.

Do you have any timeframe?  I'd like to have it in the v4.2.0 release (I'm planning to release in about two weeks), if possible.

[1]:  https://www.streebog.net
[2]:  https://github.com/adegtyarev/streebog

**Comment by vt-alt** [comment]
We could replace algo if you prefer. Also, I don't have time prediction and already switched to other projects. Two weeks is too optimistic. Maybe two months? I will post here when I start working on it.

**Comment by besser82** [comment]
@vt-alt @ldv-alt @solardiz The current implementation of gost-yescrypt in ALT Linux has one flaw:  Hashing the same phrase with the output of gost-yescrypt leads to a different hash.

**Comment by besser82** [comment]
This patch solves the issue:

```
--- crypt-gost-yescrypt.c.orig	2018-07-04 23:58:47.000000000 +0200
+++ crypt-gost-yescrypt.c	2018-10-23 21:59:14.659820653 +0200
@@ -135,8 +135,8 @@
 	 */
 	uint8_t hk[32], interm[32];
 	gost_hash256((uint8_t *)phrase, strlen(phrase), hk);
-	gost_hmac256(hk, sizeof(hk), (uint8_t *)setting, strlen(setting),
-	    interm);
+	gost_hmac256(hk, sizeof(hk), (const uint8_t *)setting,
+	    (size_t)((uint8_t *)hptr - retval), interm);
         outer_gost_hmac256(interm, sizeof(interm), y, sizeof(y), y);
 
 	encode64((uint8_t *)hptr, o_size - ((uint8_t *)hptr - output),
```

The patch actually always uses `$gy$param$salt` instead of `$gy$param$salt$output` for the inner hmac; otherwise one cannot verify the phrase against the computed hash from gost-yescrypt, without truncating setting *before* passing it crypt().

@vt-alt @ldv-alt @solardiz What do you think?

**Comment by solardiz** [comment]
This certainly looks like a bug to me. Thanks for finding it. As I understand, with the fix we're still including the whole setting string in the `gost_hmac256()` call, which has pros (simpler code now; ensures every parameter change will result in a different hash, even if the specific change is somehow otherwise a no-op) and cons (more complex code later if anyone ever needs to implement gost-yescrypt without this string encoding). I'll expect @vt-alt to review the code change and decide on whether to accept this fix or do anything differently. I have no use for gost-yescrypt hashes myself, so I am not reviewing the code closely, even though I suggested the general approach of how to wrap the whole yescrypt in GOST.

**Comment by solardiz** [comment]
Actually, I am surprised this bug could have existed so far: it'd result in authentication always failing, right? Has the code never been tested as part of the ALT Linux distro? Or is this bug in a different revision of the code than what's in the distro?

**Comment by besser82** [comment]
Yes, it results in authentication will fail, *if* one passes the whole output of crypt() as setting.  If setting is truncated to `$gy$param$salt` authentication works.

The code was taken from a recent checkout of http://git.altlinux.org/people/iv/packages/?p=libcrypt.git, so I assume it is in a recent release of ALT Linux.

**Comment by vt-alt** [comment]
Yes, it's a bug. I just tested myself in the actual installation. It is released in development repo (Sisyphus), probably @ldv-alt decided not to enable it by default, so coverage is small and we did not have any bug reports about it. Also, testers probably missed it due to it being non-default. @besser82 thank you very much!

**Comment by besser82** [comment]
@vt-alt Are you fine with my patch?

**Comment by besser82** [comment]
Let's take further discussion over to the PR.

**Comment by vt-alt** [comment]
I just assigned `OVE-20181024-0001` [ID](https://www.openwall.com/ove/) to this bug, in case it needs referencing in changelogs as a security-related bug.

**Comment by solardiz** [comment]
@vt-alt Thank you for promoting OVE IDs, but I think "authentication always fails" is not a security issue.

**Comment by besser82** [comment]
> @besser82 thank you very much!

You're very welcome!  =)

Btw, my patches posted in https://github.com/besser82/libxcrypt/issues/33#issuecomment-432400024 and https://github.com/besser82/libxcrypt/issues/33#issuecomment-432404968 apply directly on the codebase from ALT Linux.
