### ISSUE TITLE
CPU time cost below minimum raises EINVAL; glibc quietly upped it to the minimum.

### ISSUE THREAD

**Issue by t184256** [besser82/libxcrypt#89]
I was testing libxcrypt with the test vectors taken from glibc/crypt/*-test.c, and two of them resulted in a different behaviour, namely the two with the CPU cost value below the algorithm's allowed minimum. Seems like glibc sneakily bumped it to the allowed minimum, while libxcrypt returns EINVAL.

Test vectors:

    crypt("the minimum number is still observed", "$5$rounds=10$roundstoolow")
        == "$5$rounds=1000$roundstoolow$yfvwcWrQ8l/K0DAWyuPMDNHpIVlTQebY9l/gL972bIC"

    crypt( "the minimum number is still observed"","$6$rounds=10$roundstoolow")
        == "$6$rounds=1000$roundstoolow$kUMsbe306n21p9R.FRkW3IGn.S9NPN0x50YhH1xhLsPuWGsUSklZt58jaTfF4ZEQpyUNGc0dqbpBYYBaHHrsX."

BTW, do you aim for complete compatibility with glibc's crypt or is this a non-goal?

<details><summary>example reproducer</summary><p>

``` c
#include <assert.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>

#include <crypt.h>

int main() {
        errno = 0;
        char* hash = crypt("the minimum number is still observed", "$5$rounds=10$roundstoolow");

        int err = errno;
        if (err > 0) {
                perror("crypt");
                return 1;
        }

        assert(hash);
        printf("hash=%s\n", hash);
}

// crypt: Invalid argument
```
</details>

**Comment by solardiz** [comment]
Thank you for pointing out this difference. I think "complete compatibility with glibc's crypt" is a non-goal; compatibility within reason is a goal. I think we shouldn't migrate misfeatures like this from glibc to libxcrypt unless desirable for real-world usage scenarios (not just tests).

**Comment by solardiz** [comment]
I suggest we close this issue. (Technically, I could close it myself, but I'd rather leave that to those more active with the project.)

**Comment by zackw** [comment]
This was an intentional behavior change.  Silently increasing a cost parameter creates a potential interoperability problem.  Suppose two hosts are sharing the same password database (via NIS or similar protocol), and one of them silently increases cost parameters below some threshold, and the other *accepts* those cost parameters.  If a user last changed their password on the host that accepts the low cost parameters, they will mysteriously be unable to log in on the host that silently increases them.  glibc's silent increases for $5$ and $6$ hashes weren't documented, so a clean-room implementation could plausibly accept the low values unmodified.  So I'm putting a stake in the ground and saying that setting strings with low cost parameters are actually invalid.

In the default configuration, we aim to be backward compatible with as many *existing hashed passphrases* as possible, and with existing programs that use `crypt` reasonably, but we do not promise bug-for-bug compatibility with any existing implementation.  This is a security-critical library and the existing implementations that we're replacing (e.g. glibc) have not been well-maintained in the past; to promise bug-for-bug compatibility would be to risk being unable to fix actual vulnerabilities.

I'm going to go ahead and close the issue.
